// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.sessionId
  "sessionId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthLoginWithCode
export const AuthLoginWithCode = z.object({
  // Name: AuthLoginWithCode.token
  "token": z.string(),
});
export type AuthLoginWithCode = z.infer<typeof AuthLoginWithCode>;

// Name: AuthLoginWithCodeBody
export const AuthLoginWithCodeBody = z.object({
  // Name: AuthLoginWithCodeBody.code
  "code": z.string(),
  // Name: AuthLoginWithCodeBody.state
  "state": z.string(),
});
export type AuthLoginWithCodeBody = z.infer<typeof AuthLoginWithCodeBody>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: GetAllApiTokens
export const GetAllApiTokens = z.object({
  // Name: GetAllApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetAllApiTokens = z.infer<typeof GetAllApiTokens>;

// Name: GetAuthCode
export const GetAuthCode = z.object({
  // Name: GetAuthCode.code
  "code": z.string().nullable(),
});
export type GetAuthCode = z.infer<typeof GetAuthCode>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.username
  "username": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.quickPlaylist
  "quickPlaylist": z.string().nullable(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: UpdateUserSettingsBody
export const UpdateUserSettingsBody = z.object({
  // Name: UpdateUserSettingsBody.displayName
  "displayName": z.string().nullable().optional(),
});
export type UpdateUserSettingsBody = z.infer<typeof UpdateUserSettingsBody>;

