// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: AuthClaimQuickConnectCodeBody
export const AuthClaimQuickConnectCodeBody = z.object({
  // Name: AuthClaimQuickConnectCodeBody.code
  "code": z.string(),
});
export type AuthClaimQuickConnectCodeBody = z.infer<typeof AuthClaimQuickConnectCodeBody>;

// Name: AuthFinishProvider
export const AuthFinishProvider = z.object({
  // Name: AuthFinishProvider.token
  "token": z.string(),
});
export type AuthFinishProvider = z.infer<typeof AuthFinishProvider>;

// Name: AuthFinishProviderBody
export const AuthFinishProviderBody = z.object({
  // Name: AuthFinishProviderBody.requestId
  "requestId": z.string(),
  // Name: AuthFinishProviderBody.challenge
  "challenge": z.string(),
});
export type AuthFinishProviderBody = z.infer<typeof AuthFinishProviderBody>;

// Name: AuthFinishQuickConnect
export const AuthFinishQuickConnect = z.object({
  // Name: AuthFinishQuickConnect.token
  "token": z.string(),
});
export type AuthFinishQuickConnect = z.infer<typeof AuthFinishQuickConnect>;

// Name: AuthFinishQuickConnectBody
export const AuthFinishQuickConnectBody = z.object({
  // Name: AuthFinishQuickConnectBody.code
  "code": z.string(),
  // Name: AuthFinishQuickConnectBody.challenge
  "challenge": z.string(),
});
export type AuthFinishQuickConnectBody = z.infer<typeof AuthFinishQuickConnectBody>;

// Name: AuthGetProviderStatus
export const AuthGetProviderStatus = z.object({
  // Name: AuthGetProviderStatus.status
  "status": z.string(),
});
export type AuthGetProviderStatus = z.infer<typeof AuthGetProviderStatus>;

// Name: AuthGetProviderStatusBody
export const AuthGetProviderStatusBody = z.object({
  // Name: AuthGetProviderStatusBody.requestId
  "requestId": z.string(),
  // Name: AuthGetProviderStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetProviderStatusBody = z.infer<typeof AuthGetProviderStatusBody>;

// Name: AuthGetQuickConnectStatus
export const AuthGetQuickConnectStatus = z.object({
  // Name: AuthGetQuickConnectStatus.status
  "status": z.string(),
});
export type AuthGetQuickConnectStatus = z.infer<typeof AuthGetQuickConnectStatus>;

// Name: AuthGetQuickConnectStatusBody
export const AuthGetQuickConnectStatusBody = z.object({
  // Name: AuthGetQuickConnectStatusBody.code
  "code": z.string(),
  // Name: AuthGetQuickConnectStatusBody.challenge
  "challenge": z.string(),
});
export type AuthGetQuickConnectStatusBody = z.infer<typeof AuthGetQuickConnectStatusBody>;

// Name: AuthInitiate
export const AuthInitiate = z.object({
  // Name: AuthInitiate.requestId
  "requestId": z.string(),
  // Name: AuthInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthInitiate.challenge
  "challenge": z.string(),
  // Name: AuthInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthInitiate = z.infer<typeof AuthInitiate>;

// Name: AuthInitiateBody
export const AuthInitiateBody = z.object({
  // Name: AuthInitiateBody.providerId
  "providerId": z.string(),
});
export type AuthInitiateBody = z.infer<typeof AuthInitiateBody>;

// Name: AuthProvider
export const AuthProvider = z.object({
  // Name: AuthProvider.id
  "id": z.string(),
  // Name: AuthProvider.displayName
  "displayName": z.string(),
});
export type AuthProvider = z.infer<typeof AuthProvider>;

// Name: AuthQuickConnectInitiate
export const AuthQuickConnectInitiate = z.object({
  // Name: AuthQuickConnectInitiate.code
  "code": z.string(),
  // Name: AuthQuickConnectInitiate.challenge
  "challenge": z.string(),
  // Name: AuthQuickConnectInitiate.authUrl
  "authUrl": z.string(),
  // Name: AuthQuickConnectInitiate.expiresAt
  "expiresAt": z.string(),
});
export type AuthQuickConnectInitiate = z.infer<typeof AuthQuickConnectInitiate>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: GetAllApiTokens
export const GetAllApiTokens = z.object({
  // Name: GetAllApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetAllApiTokens = z.infer<typeof GetAllApiTokens>;

// Name: GetAuthProviders
export const GetAuthProviders = z.object({
  // Name: GetAuthProviders.providers
  "providers": z.array(AuthProvider),
});
export type GetAuthProviders = z.infer<typeof GetAuthProviders>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.email
  "email": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
  // Name: GetMe.role
  "role": z.string(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: UpdateUserSettingsBody
export const UpdateUserSettingsBody = z.object({
  // Name: UpdateUserSettingsBody.displayName
  "displayName": z.string().nullable().optional(),
});
export type UpdateUserSettingsBody = z.infer<typeof UpdateUserSettingsBody>;

