package service

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/coreos/go-oidc/v3/oidc"
	"github.com/golang-jwt/jwt/v5"
	"github.com/nanoteck137/authlab/config"
	"github.com/nanoteck137/authlab/database"
	"github.com/nanoteck137/authlab/tools/utils"
	"golang.org/x/oauth2"
)

type ServiceError struct {
	Service string
	Err     error
}

func (e *ServiceError) Error() string {
	return fmt.Sprintf("%s: %s", e.Service, e.Err)
}

type ServiceErrCreator struct {
	Service string
}

func NewServiceErrCreator(service string) ServiceErrCreator {
	return ServiceErrCreator{
		Service: service,
	}
}

func (s *ServiceErrCreator) Error(text string) error {
	return &ServiceError{
		Service: s.Service,
		Err:     errors.New(text),
	}
}

func (s *ServiceErrCreator) Errorf(format string, a ...any) error {
	return &ServiceError{
		Service: s.Service,
		Err:     fmt.Errorf(format, a...),
	}
}

var authErr = NewServiceErrCreator("auth-service")

var (
	ErrAuthServiceProviderNotFound = authErr.Error("provider not found")

	ErrAuthServiceRequestAlreadyExists = authErr.Error("request already exists")
	ErrAuthServiceRequestNotFound      = authErr.Error("request not found")
	ErrAuthServiceRequestExpired       = authErr.Error("request is expired")
	ErrAuthServiceRequestNotReady      = authErr.Error("request is not ready")
	ErrAuthServiceRequestInvalid       = authErr.Error("request is invalid")
)

const (
	AuthProviderRequestExpireDuration   = 5 * time.Minute
	AuthProviderRequestDeletionDuration = AuthProviderRequestExpireDuration + 10*time.Minute

	AuthQuickRequestExpireDuration   = 5 * time.Minute
	AuthQuickRequestDeletionDuration = AuthQuickRequestExpireDuration + 10*time.Minute
)

type AuthProviderRequestStatus string

const (
	AuthProviderRequestStatusPending   AuthProviderRequestStatus = "pending"
	AuthProviderRequestStatusCompleted AuthProviderRequestStatus = "completed"
	AuthProviderRequestStatusExpired   AuthProviderRequestStatus = "expired"
	AuthProviderRequestStatusFailed    AuthProviderRequestStatus = "failed"
)

type AuthQuickRequestStatus string

const (
	AuthQuickRequestStatusPending   AuthQuickRequestStatus = "pending"
	AuthQuickRequestStatusCompleted AuthQuickRequestStatus = "completed"
	AuthQuickRequestStatusExpired   AuthQuickRequestStatus = "expired"
	AuthQuickRequestStatusFailed    AuthQuickRequestStatus = "failed"
)

// TODO(patrik): Change the fields to private
type AuthProviderRequest struct {
	Id         string
	ProviderId string

	Status AuthProviderRequestStatus

	challenge string

	OAuth2Url  string
	OAuth2Code string

	QuickCode string

	Expires time.Time
	Delete  time.Time
}

type AuthProvider struct {
	initialized bool

	Id          string
	DisplayName string

	config config.ConfigOidcProvider

	provider     *oidc.Provider
	oauth2Config *oauth2.Config
	verifier     *oidc.IDTokenVerifier
}

func (p *AuthProvider) init(ctx context.Context) error {
	if p.initialized {
		return nil
	}

	var err error

	p.provider, err = oidc.NewProvider(ctx, p.config.IssuerUrl)
	if err != nil {
		return err
	}

	p.oauth2Config = &oauth2.Config{
		ClientID:     p.config.ClientId,
		ClientSecret: p.config.ClientSecret,
		RedirectURL:  p.config.RedirectUrl,
		Endpoint:     p.provider.Endpoint(),
		Scopes:       []string{oidc.ScopeOpenID, "profile", "email"},
	}

	p.verifier = p.provider.Verifier(&oidc.Config{ClientID: p.config.ClientId})

	p.initialized = true

	return nil
}

type providerClaim struct {
	Email       string `json:"email"`
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Picture     string `json:"picture"`
	Sub         string `json:"sub"`
}

func (p *AuthProvider) claim(ctx context.Context, code string) (providerClaim, error) {
	oauth2Token, err := p.oauth2Config.Exchange(ctx, code)
	if err != nil {
		return providerClaim{}, err
	}

	rawIDToken, ok := oauth2Token.Extra("id_token").(string)
	if !ok {
		return providerClaim{}, errors.New("oauth2 token is missing id_token")
	}

	idToken, err := p.verifier.Verify(ctx, rawIDToken)
	if err != nil {
		return providerClaim{}, err
	}

	var claims providerClaim
	err = idToken.Claims(&claims)
	if err != nil {
		return providerClaim{}, err
	}

	return claims, nil
}

type AuthQuickConnectRequest struct {
	// the status of the request
	status AuthQuickRequestStatus

	// the code of this request, generated by GenerateCode
	// example "ABCD-1234-EFGH"
	code string

	// small token generated by GenerateAuthChallenge and is returned
	// to the client when initiating, then is checked when trying to
	// create the JWT token
	challenge string

	// This is set then status == completed, and is the userId of
	// the user that authorized the request
	userId string

	// the expiry date of this request
	expires time.Time

	// the date of then we can delete this request
	delete time.Time
}

type AuthService struct {
	mu sync.Mutex

	db        *database.Database
	jwtSecret string

	providers map[string]*AuthProvider

	ProviderRequests     map[string]*AuthProviderRequest
	QuickConnectRequests map[string]*AuthQuickConnectRequest
}

func NewAuthService(db *database.Database, config *config.Config) *AuthService {
	providers := make(map[string]*AuthProvider, len(config.OidcProviders))

	for id, providerConfig := range config.OidcProviders {
		res := &AuthProvider{
			Id:          id,
			DisplayName: providerConfig.Name,
			config:      providerConfig,
		}

		providers[id] = res
	}

	return &AuthService{
		db:                   db,
		jwtSecret:            config.JwtSecret,
		providers:            providers,
		ProviderRequests:     make(map[string]*AuthProviderRequest),
		QuickConnectRequests: make(map[string]*AuthQuickConnectRequest),
	}
}

type ProviderRequestResult struct {
	RequestId string
	AuthUrl   string
	Challenge string
	Expires   time.Time
}

func (a *AuthService) CreateProviderRequest(providerId string) (ProviderRequestResult, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	provider, exists := a.providers[providerId]
	if !exists {
		return ProviderRequestResult{}, ErrAuthServiceProviderNotFound
	}

	err := provider.init(context.TODO())
	if err != nil {
		return ProviderRequestResult{}, authErr.Errorf("initialize AuthProvider(%s): %w", provider.Id, err)
	}

	challenge, err := utils.GenerateAuthChallenge()
	if err != nil {
		return ProviderRequestResult{}, authErr.Errorf("generate auth challenge: %w", err)
	}

	id := utils.CreateId()

	t := time.Now()
	request := &AuthProviderRequest{
		Id:         id,
		ProviderId: provider.Id,
		Status:     AuthProviderRequestStatusPending,
		challenge:  challenge,
		Expires:    t.Add(AuthProviderRequestExpireDuration),
		Delete:     t.Add(AuthProviderRequestDeletionDuration),
	}

	request.OAuth2Url = provider.oauth2Config.AuthCodeURL(request.Id)

	_, exists = a.ProviderRequests[id]
	if exists {
		return ProviderRequestResult{}, ErrAuthServiceRequestAlreadyExists
	}

	a.ProviderRequests[id] = request

	return ProviderRequestResult{
		RequestId: request.Id,
		AuthUrl:   request.OAuth2Url,
		Challenge: request.challenge,
		Expires:   request.Expires,
	}, nil
}

type QuickConnectRequestResult struct {
	Code      string
	Challenge string
	Expires   time.Time
}

func (a *AuthService) CreateQuickConnectRequest() (QuickConnectRequestResult, error) {
	code, err := utils.GenerateCode()
	if err != nil {
		return QuickConnectRequestResult{}, fmt.Errorf("failed to generate code: %w", err)
	}

	challenge, err := utils.GenerateAuthChallenge()
	if err != nil {
		return QuickConnectRequestResult{}, fmt.Errorf("failed to generate challenge: %w", err)
	}

	t := time.Now()
	request := &AuthQuickConnectRequest{
		status:    AuthQuickRequestStatusPending,
		code:      code,
		challenge: challenge,
		expires:   t.Add(AuthQuickRequestExpireDuration),
		delete:    t.Add(AuthQuickRequestDeletionDuration),
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	_, exists := a.QuickConnectRequests[code]
	if exists {
		return QuickConnectRequestResult{}, err
	}

	a.QuickConnectRequests[code] = request

	return QuickConnectRequestResult{
		Code:      request.code,
		Challenge: request.challenge,
		Expires:   request.expires,
	}, nil
}

func (a *AuthService) CompleteQuickConnectRequest(requestCode, userId string) error {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.QuickConnectRequests[requestCode]
	if !exists {
		return ErrAuthServiceRequestNotFound
	}

	if time.Now().After(request.expires) {
		request.status = AuthQuickRequestStatusExpired
		return ErrAuthServiceRequestExpired
	}

	if request.status == AuthQuickRequestStatusPending {
		request.status = AuthQuickRequestStatusCompleted
		request.userId = userId
	}

	return nil
}

func (a *AuthService) CompleteProviderRequest(requestId, code string) error {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.ProviderRequests[requestId]
	if !exists {
		return ErrAuthServiceRequestNotFound
	}

	if time.Now().After(request.Expires) {
		request.Status = AuthProviderRequestStatusExpired
		return ErrAuthServiceRequestExpired
	}

	if request.Status == AuthProviderRequestStatusPending {
		request.Status = AuthProviderRequestStatusCompleted
		request.OAuth2Code = code
	}

	return nil
}

func (a *AuthService) CheckProviderRequestStatus(requestId, challenge string) (AuthProviderRequestStatus, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.ProviderRequests[requestId]
	if !exists {
		return AuthProviderRequestStatusFailed, ErrAuthServiceRequestNotFound
	}

	if request.challenge != challenge {
		// TODO(patrik): Give this it's own error
		return AuthProviderRequestStatusFailed, ErrAuthServiceRequestNotFound
	}

	now := time.Now()
	if now.After(request.Expires) {
		request.Status = AuthProviderRequestStatusExpired
	}

	return request.Status, nil
}

func (a *AuthService) CheckQuickConnectRequestStatus(requestCode, challenge string) (AuthQuickRequestStatus, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.QuickConnectRequests[requestCode]
	if !exists {
		return AuthQuickRequestStatusFailed, ErrAuthServiceRequestNotFound
	}

	if request.challenge != challenge {
		return AuthQuickRequestStatusFailed, ErrAuthServiceRequestNotFound
	}

	now := time.Now()
	if now.After(request.expires) {
		request.status = AuthQuickRequestStatusExpired
	}

	return request.status, nil
}

func (a *AuthService) CreateAuthTokenForProvider(requestId, challenge string) (string, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.ProviderRequests[requestId]
	if !exists {
		return "", ErrAuthServiceRequestNotFound
	}

	if request.challenge != challenge {
		return "", ErrAuthServiceRequestNotFound
	}

	if request.Status != AuthProviderRequestStatusCompleted {
		return "", ErrAuthServiceRequestNotReady
	}

	// TODO(patrik): Check provider?
	provider := a.providers[request.ProviderId]

	code := request.OAuth2Code

	userId, err := a.getUserFromCode(context.TODO(), provider, code)
	if err != nil {
		return "", err
	}

	if userId == "" {
		return "", ErrAuthServiceRequestInvalid
	}

	request.Status = AuthProviderRequestStatusExpired

	token, err := a.SignUserToken(userId)
	if err != nil {
		return "", err
	}

	return token, nil
}

func (a *AuthService) CreateAuthTokenForQuickConnect(requestCode, challenge string) (string, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	request, exists := a.QuickConnectRequests[requestCode]
	if !exists {
		return "", ErrAuthServiceRequestNotFound
	}

	if request.challenge != challenge {
		return "", ErrAuthServiceRequestNotFound
	}

	if request.status != AuthQuickRequestStatusCompleted {
		return "", ErrAuthServiceRequestInvalid
	}

	if request.userId == "" {
		return "", ErrAuthServiceRequestInvalid
	}

	request.status = AuthQuickRequestStatusExpired

	token, err := a.SignUserToken(request.userId)
	if err != nil {
		return "", err
	}

	return token, nil
}

func (a *AuthService) getUserFromCode(ctx context.Context, provider *AuthProvider, code string) (string, error) {
	oidcClaims, err := provider.claim(ctx, code)
	if err != nil {
		return "", err
	}

	getOrCreateUser := func() (string, error) {
		user, err := a.db.GetUserByEmail(ctx, oidcClaims.Email)
		if err != nil {
			if errors.Is(err, database.ErrItemNotFound) {
				displayName := oidcClaims.DisplayName
				if displayName == "" {
					displayName = oidcClaims.Name
				}

				user, err = a.db.CreateUser(ctx, database.CreateUserParams{
					Email:       oidcClaims.Email,
					DisplayName: displayName,
					Role:        "user",
				})
				if err != nil {
					return "", err
				}

				return user.Id, nil
			} else {
				return "", err
			}
		}

		return user.Id, nil
	}

	identity, err := a.db.GetUserIdentity(ctx, provider.Id, oidcClaims.Sub)
	if err != nil {
		if errors.Is(err, database.ErrItemNotFound) {
			userId, err := getOrCreateUser()
			if err != nil {
				return "", err
			}

			err = a.db.CreateUserIdentity(ctx, database.CreateUserIdentityParams{
				Provider:   provider.Id,
				ProviderId: oidcClaims.Sub,
				UserId:     userId,
			})
			if err != nil {
				return "", err
			}

			return userId, nil
		} else {
			return "", err
		}
	}

	return identity.UserId, nil
}

func (a *AuthService) SignUserToken(userId string) (string, error) {
	// TODO(patrik): Errors
	user, err := a.db.GetUserById(context.Background(), userId)
	if err != nil {
		return "", err
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"userId": user.Id,
		"iat":    time.Now().Unix(),
		// "exp":    time.Now().Add(1000 * time.Second).Unix(),
	})

	tokenString, err := token.SignedString(([]byte)(a.jwtSecret))
	if err != nil {
		return "", err
	}

	return tokenString, nil
}

func (a *AuthService) RemoveUnusedEntries() {
	a.mu.Lock()
	defer a.mu.Unlock()

	now := time.Now()
	for k, request := range a.ProviderRequests {
		if now.After(request.Delete) {
			delete(a.ProviderRequests, k)
		}
	}

	for k, request := range a.QuickConnectRequests {
		if now.After(request.delete) {
			delete(a.QuickConnectRequests, k)
		}
	}
}

// TODO(patrik): This should be a worker that the app creates when initializing
func (a *AuthService) CleanRoutine() {
	ticker := time.NewTicker(30 * time.Minute)
	for range ticker.C {
		slog.Info("auth-service: running cleanup")
		a.RemoveUnusedEntries()
	}
}
